// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaVirtual.Models
{
    public partial class ArticulosPorTienda
    {
        public int Id { get; set; }
        public int IdArticulo { get; set; }
        public int IdTienda { get; set; }
        public DateTime? Fecha { get; set; }

        public virtual Articulos IdArticuloNavigation { get; set; }
        public virtual Tienda IdTiendaNavigation { get; set; }
    }
}